uses
    Classes, SysUtils;

{procedure TestStringList;}

var 
    Dictionary: TStringList;
    name: String;
    answer:  String;
    
begin
    Dictionary := TStringList.Create;

    { add coubtry}
    Dictionary.AddPair('Россия', 'Москва');
    Dictionary.AddPair('Беларусь', 'Минск');
    Dictionary.AddPair('Ливия', 'Триполи');
    Dictionary.AddPair('Абхазия', 'Сухум');
    Dictionary.AddPair('Австралия', 'Камберра');
    Dictionary.AddPair('Австрия', 'Вена');
    Dictionary.AddPair('Азербайджан', 'Баку');
    Dictionary.AddPair('Албания', 'Тирана');
    Dictionary.AddPair('Алжир', 'Алжир');
    Dictionary.AddPair('Ангола', 'Луанда');
    Dictionary.AddPair('Андорра', 'Андорра-ла-Велья');
    Dictionary.AddPair('Антигуана и Барбуда', 'Сент-Джонс');
    Dictionary.AddPair('Аргентина', 'Буэнос-Айрес');
    Dictionary.AddPair('Армения', 'Ереван');
    Dictionary.AddPair('Аруба', 'Ораньестад');
    Dictionary.AddPair('Афганистан', 'Кабул');
    Dictionary.AddPair('Багамы', 'Нассау');
    Dictionary.AddPair('Бангландеш', 'Дака');
    Dictionary.AddPair('Барбадос', 'Бриджтаун');
    Dictionary.AddPair('Бахрейн', 'Манама');
    Dictionary.AddPair('Белиз', 'Бельмопан');
    Dictionary.AddPair('Бельгия', 'Брюссель');
    Dictionary.AddPair('Бенин', 'Порто-Ново, Котону');
    Dictionary.AddPair('Бермудские острова', 'Гамильтон');
    Dictionary.AddPair('Болгария', 'София');
    Dictionary.AddPair('Боливия', 'Сукре');
    Dictionary.AddPair('Босния и Герцеговина', 'Сараево');
    Dictionary.AddPair('Ботсвана', 'Габороне');
    Dictionary.AddPair('Бразилия', 'Бразилиа');
    Dictionary.AddPair('Бруней', 'Бандар-Сери-Бегаван');
    Dictionary.AddPair('Буркина Фасо', 'Уагадугу');
    Dictionary.AddPair('Бурунди', 'Бужумбура');
    Dictionary.AddPair('Бутан', 'Тхимпху');
    Dictionary.AddPair('Вануату', 'порт-Вила');
    Dictionary.AddPair('Ватикан', 'Ватикан');
    Dictionary.AddPair('Великобритания', 'Лондон');
    Dictionary.AddPair('венгрия', 'Будапешт');
    Dictionary.AddPair('Венесуэла', 'Каракас');
    Dictionary.AddPair('Вьетнам', 'Ханой');
    Dictionary.AddPair('Габон', 'Либревиль');
    Dictionary.AddPair('Гавайские острова', 'Гонолулу');
    Dictionary.AddPair('Гайана', 'Джорджтаун');
    Dictionary.AddPair('Гаити', 'Порт-о-Пренс');
    Dictionary.AddPair('Гамбия', 'Банжул');
    Dictionary.AddPair('Гана', 'Аккра');
    Dictionary.AddPair('Гваделупа', 'Бас-Тер');
    Dictionary.AddPair('Гватемала', 'Гватемала');
    Dictionary.AddPair('Гвинея', 'Конакри');
    Dictionary.AddPair('Гвинея-Бисау', 'Бисау');
    Dictionary.AddPair('Германия', 'Берлин');
    Dictionary.AddPair('Гондурас', 'Тегусигальпа');
    Dictionary.AddPair('Гонконг', 'Гонконг');
    Dictionary.AddPair('Гренада', 'Сент-Джорджес');
    Dictionary.AddPair('Греция', 'Афины');
    Dictionary.AddPair('Грузия', 'Тбилиси');
    Dictionary.AddPair('Дания', 'Копенгаген');
    Dictionary.AddPair('Джибути', 'Джибути');
    Dictionary.AddPair('Доминика', 'Розо');
    Dictionary.AddPair('Доминикана', 'Санто-Доминго');
    Dictionary.AddPair('Египет', 'Каир');
    Dictionary.AddPair('Замбия', 'Лусака');
    Dictionary.AddPair('Зимбабве', 'Хараре');
    Dictionary.AddPair('Израиль', 'Иерусалим');
    Dictionary.AddPair('Индия', 'Нью-Дели');
    Dictionary.AddPair('Индонезия', 'Джакарта');
    Dictionary.AddPair('Иордания', 'Амман');
    Dictionary.AddPair('Ирак', 'Багдад');
    Dictionary.AddPair('Иран', 'Тегеран');
    Dictionary.AddPair('Ирландия', 'Дублин');
    Dictionary.AddPair('Исландия', 'Рейкьявик');
    Dictionary.AddPair('Испания', 'Мадрид');
    Dictionary.AddPair('Италия', 'Рим');
    Dictionary.AddPair('Йемен', 'Сана');
    Dictionary.AddPair('Кабо-Верде', 'Прая');
    Dictionary.AddPair('Казахстан', 'Нур-Султан');
    Dictionary.AddPair('Каймановы острова', 'Джорджтаун');
    Dictionary.AddPair('Камбоджа', 'Пномпень');
    Dictionary.AddPair('Камерун', 'Яунде');
    Dictionary.AddPair('Канада', 'Оттава');
    Dictionary.AddPair('Канарские острова', 'Испания');
    Dictionary.AddPair('Катар', 'Доха');
    Dictionary.AddPair('Кения', 'Найроби');
    Dictionary.AddPair('Кипр', 'Никосия');
    Dictionary.AddPair('Киргизия', 'Бишкек');
    Dictionary.AddPair('Кирибати', 'Южная Тарава');
    Dictionary.AddPair('Китай', 'Пекин');
    Dictionary.AddPair('Колумбия', 'Санта-Фе-Де-Богота');
    Dictionary.AddPair('Коморы', 'Морони');
    Dictionary.AddPair('Конго', 'Браззавиль');
    Dictionary.AddPair('Конго-Киншаса', 'Киншаса');
    Dictionary.AddPair('Коста-Рика', 'Сан-Хосе');
    Dictionary.AddPair('Кот-д,Ивуар', 'Ямусурко');
    Dictionary.AddPair('Куба', 'Гавана');
    Dictionary.AddPair('Лаос', 'Вьентьян');
    Dictionary.AddPair('Латвия', 'Рига');
    Dictionary.AddPair('Лесото', 'Масеру');
    Dictionary.AddPair('Либерия', 'Монровия');
    Dictionary.AddPair('Ливан', 'Бейрут');
    Dictionary.AddPair('Литва', 'Вильнюс');
    Dictionary.AddPair('Лихтенштейн', 'Вадуц');
    Dictionary.AddPair('Люксембург', 'Люксембург');
    Dictionary.AddPair('Маврикий', 'Порт-Луи');
    Dictionary.AddPair('Мавритания', 'Нуакшот');
    Dictionary.AddPair('Мадагаскар', 'Антананариву');
    Dictionary.AddPair('Македония', 'Скопье');
    Dictionary.AddPair('Малави', 'Лилонгве');
    Dictionary.AddPair('Малайзия', 'куала-Лумпур');
    Dictionary.AddPair('Мали', 'Бамако');
    Dictionary.AddPair('Мальдивы', 'Мале');
    Dictionary.AddPair('Мальта', 'Валлетта');
    Dictionary.AddPair('Марокко', 'Рабат');
    Dictionary.AddPair('Мартиника', 'Фор-де-Франс');
    Dictionary.AddPair('Маршалловы острова', 'Маджуро');
    Dictionary.AddPair('Мексика', 'Мехико');
    Dictionary.AddPair('Мозамбик', 'Мапуту');
    Dictionary.AddPair('Молдова', 'Кишинев');
    Dictionary.AddPair('Монако', 'Монако');
    Dictionary.AddPair('Монголия', 'Улан-Батор');
    Dictionary.AddPair('Мьянма', 'Нейпьидо');
    Dictionary.AddPair('Намибия', 'Виндхук');
    Dictionary.AddPair('Науру', 'Ярен');
    Dictionary.AddPair('Непал', 'Катманду');
    Dictionary.AddPair('Нигер', 'Ниамей');
    Dictionary.AddPair('Нигерия', 'Абуджа');
    Dictionary.AddPair('Нидерланды', 'Амстердам');
    Dictionary.AddPair('Никарагуа', 'Манагуа');
    Dictionary.AddPair('Новая Зеландия', 'Велингтон');
    Dictionary.AddPair('Норвегия', 'Осло');
    Dictionary.AddPair('ОАЭ', 'Абу-Даби');
    Dictionary.AddPair('Оман', 'Маскат');
    Dictionary.AddPair('Остров Святой Елены', 'Джеймстаун');
    Dictionary.AddPair('Пакистан', 'Исламабад');
    Dictionary.AddPair('Палау', 'Нгерулдум');
    Dictionary.AddPair('Панама', 'Памана');
    Dictionary.AddPair('Папуа-Новая Гвинея', 'Порт-Морсби');
    Dictionary.AddPair('Парагвай', 'Асунсьон');
    Dictionary.AddPair('Перу', 'Лима');
    Dictionary.AddPair('Польша', 'Варшава');
    Dictionary.AddPair('Португалия', 'Лиссабон');
    Dictionary.AddPair('Пуэрто-Рико', 'Сан-Хуан');
    Dictionary.AddPair('Реюньон', 'Сен-Дени');
    Dictionary.AddPair('Руанда', 'Кигали');
    Dictionary.AddPair('Румыния', 'Бухарест');
    Dictionary.AddPair('Сальвадор', 'Сан-Сальвадор');
    Dictionary.AddPair('Самоа', 'Апиа');
    Dictionary.AddPair('Сан-Марино', 'Сан-Марино');
    Dictionary.AddPair('Сан-Томе', 'Сан-Томе');
    Dictionary.AddPair('Саудовская Аравия', 'Эр-Рияд');
    Dictionary.AddPair('Свазиленд', 'Мбабане, Лобамба');
    Dictionary.AddPair('Северная Корея', 'Пхеньян');
    Dictionary.AddPair('Северная Македония', 'Скопье');
    Dictionary.AddPair('Сейшелы', 'Виктория');
    Dictionary.AddPair('Сенегал', 'Дакар');
    Dictionary.AddPair('Сен-Мартен', 'Мариго');
    Dictionary.AddPair('Сент-Винсент и Гренадины', 'Кингстаун');
    Dictionary.AddPair('Сент-Китс', 'Бастер');
    Dictionary.AddPair('Сент-Люсия', 'Кастри');
    Dictionary.AddPair('Сербия', 'Белград');
    Dictionary.AddPair('Сингапур', 'Сингапур');
    Dictionary.AddPair('Сирия', 'Дамаск');
    Dictionary.AddPair('Словакия', 'Братислава');
    Dictionary.AddPair('Словения', 'Любляна');
    Dictionary.AddPair('Соломоновы острова', 'Хониара');
    Dictionary.AddPair('Сомали', 'Могадишо');
    Dictionary.AddPair('Судан', 'Хартум');
    Dictionary.AddPair('Суринам', 'Парамарибо');
    Dictionary.AddPair('США', 'Вашингтон');
    Dictionary.AddPair('Сьерра-Леоне', 'Фритаун');
    Dictionary.AddPair('Таджикистан', 'Душанбе');
    Dictionary.AddPair('Тайвань', 'Тайбэй');
    Dictionary.AddPair('Тайланд', 'Бангкок');
    Dictionary.AddPair('Танзания', 'Додома');
    Dictionary.AddPair('Того', 'Ломе');
    Dictionary.AddPair('Тонга', 'Нукуалофа');
    Dictionary.AddPair('Тринидад', 'Порт-оф-Спейн');
    Dictionary.AddPair('Тувалу', 'Фунафути');
    Dictionary.AddPair('Тунис', 'Тунис');
    Dictionary.AddPair('Туркменистан', 'Ашхадаб');
    Dictionary.AddPair('Турция', 'Анкара');
    Dictionary.AddPair('Уганда', 'Кампала');
    Dictionary.AddPair('Узбекистан', 'Ташкент');
    Dictionary.AddPair('Украина', 'Киев');
    Dictionary.AddPair('Уоллис', 'Мата-Уту');
    Dictionary.AddPair('Уругвай', 'Монтевидео');
    Dictionary.AddPair('Фиджи', 'Сува');
    Dictionary.AddPair('Филиппины', 'Манила');
    Dictionary.AddPair('Финляндия', 'Хельсинки');
    Dictionary.AddPair('Франция', 'Париж');
    Dictionary.AddPair('Французская Гвиана', 'Кайенна');
    Dictionary.AddPair('Хорватия', 'Загреб');
    Dictionary.AddPair('Центрально-африканская республика', 'Банги');
    Dictionary.AddPair('Чад', 'Нджамена');
    Dictionary.AddPair('Черногория', 'Подгорница');
    Dictionary.AddPair('Чехия', 'Прага');
    Dictionary.AddPair('Чили', 'Сантьяго');
    Dictionary.AddPair('Швейцария', 'Берн');
    Dictionary.AddPair('Швеция', 'Стокгольм');
    Dictionary.AddPair('Шри-Ланка', 'Шри-Джаяварденепура-Котте');
    Dictionary.AddPair('Эквадор', 'Кито');
    Dictionary.AddPair('Экваториальная Гвинея', 'Малабо');
    Dictionary.AddPair('Эритрея', 'Асмэра');
    Dictionary.AddPair('Эстония', 'Таллин');
    Dictionary.AddPair('Эфиопия', 'Аддис-Абеба');
    Dictionary.AddPair('ЮАР', 'Кейптаун Претория');
    Dictionary.AddPair('Южная Корея', 'Сеул');
    Dictionary.AddPair('Ямайка', 'Кингстон');
    Dictionary.AddPair('Япония', 'Токио');


    {input country}
    Writeln('Введите название страны: ');
    Readln(name);

    answer := Dictionary.Values[name];
    Writeln('Столица страны '+ name + ': ' + answer);

end.
